settings:
  timeframe: '15min'                 # e.g., '1hour', '4hour', '1day'
  start_date: '2025-01-01' # YYYY-MM-DD format
  end_date: '2025-08-15' # YYYY-MM-DD format
  twelvedata_api_key: 'ee7903749ba2480d9bd749be16cc6b23' # <-- IMPORTANT: Replace with your key

pairs_to_analyze:
  - ['IBIT:Nasdaq', 'BTC/USD:Binance']
  - ['COIN:Nasdaq', 'BTC/USD:Binance']
